services:
  postgres:
    image: postgres:18.1
    container_name: mental-math-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mental_math
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql
  # # Node.js service (use with: docker compose up mental-math-nextjs --build)
  # mental-math-nextjs:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   image: nextjs-standalone-image
  #   container_name: mental-math-nextjs
  #   environment:
  #     NODE_ENV: production
  #     PORT: "3000"
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/mental_math
  #     BETTER_AUTH_SECRET: ${BETTER_AUTH_SECRET:?BETTER_AUTH_SECRET is required}
  #     BETTER_AUTH_URL: ${BETTER_AUTH_URL:-http://localhost:3000}
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - postgres
  #   restart: unless-stopped

volumes:
  postgres_data:
